---
title: "carib_results"
author: "Lennon Thomas"
date: "2/8/2018"
output: html_document
---

```{r setup, warning=FALSE , echo=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = F, warning = F, fig.width = 6.5)
```


```{r echo = FALSE}
# Load packages and functions-----------------------------------------------------------
rm(list = ls())

library(broom)
library(tidyverse)
library(parallel)
library(pander)
library(ggridges)
library(skimr)
library(viridis)
library(RColorBrewer)
library(ggrepel)
library(scales)

# Run settings -------------------------------------------------------------

## Set User (lennon/tyler)
user <- 'tyler'

if(user == 'lennon') { boxdir <- '/Users/lennonthomas/Box Sync/Waitt Institute/Blue Halo 2016/Carib_aqua_16/'}
if(user == 'tyler')  { boxdir <-  '../../Box Sync/Carib_aqua_16/'}

run_name = 'est_feb_8'  

# Load run results 
# "calc_0.02" #run name reflects intital stocking density (calculated or fixed)and feed rates (as % body weight)
result_folder <- paste0(boxdir,'results/',run_name,"/Results")
file.names <- list.files(path = result_folder, pattern = ".csv")
result_files <- lapply(paste0(result_folder,"/",file.names),read_csv)

# Extract individual result data sets
carib_supply <- result_files[[1]]
eez_supply_df <- result_files[[2]]
cashflow <- result_files[[3]]
npv_df <- result_files[[4]]
sim_results <- result_files[[5]]
supply_summary<-result_files[[6]]
```



## NPV per farm by price and discount rate

```{r}
# Extract only farms (cells) with positive NPV
pos_npv <- filter(npv_df, npv > 0)
```


### Caribbean wide

```{r}
# Summarize NPV by price and discount options
npv_summary <- pos_npv %>% 
  select(prices, discounts, npv, total_harvest) %>% 
  group_by(prices, discounts) %>% 
  skim()

# Caribbean NPV summary table
npv_summary %>% 
  select(-type, -level, - formatted) %>% 
  filter(stat %in% c('median', 'mean','sd', 'p75', 'p100')) %>% 
  spread(stat, value) %>% 
  arrange(prices, variable)
  
```


```{r}
pos_npv %>%  
  ggplot(aes(x = npv)) +
  geom_density() +
  facet_grid(prices ~ discounts, scales = 'free_y')
```


### By country

```{r}
# Country level NPV summary
npv_cntry_summary <- pos_npv %>% 
  select(country, prices, discounts, npv, total_harvest) %>% 
  group_by(country, prices, discounts) %>% 
  skim()
```

```{r}
# Pull out base scenario results from NPV ($8.62 and 0% discount results)
main_npv <- filter(pos_npv, prices == 8.62 & discounts == 0)
```


```{r}
# Country total NPV and farms 
dense_df1 <- main_npv %>%
  group_by(country) %>% 
  mutate(total_npv = sum(npv, na.rm = T),
         farms     = length(unique(cell))) %>% 
  ungroup() %>% 
  mutate(discounts = factor(discounts))

# ridge plot of NPV by EEZ
dense_df1 %>% 
  ggplot(aes(x = npv, fill = log10(total_npv))) +
  geom_density_ridges2(aes(y = fct_reorder(country, npv, fun = median)), alpha = 0.8) +
  scale_x_continuous(limits = c(0,NA), expand = c(0,0)) +
  scale_fill_viridis() +
  labs(title = 'NPV of cobia aquaculture by Caribbean EEZ',
       x     = 'Net Present Value (NPV)',
       y     = NULL,
       fill  = paste0('NPV (log)')) +
  theme_minimal()

```

### Costs by EEZ
```{r}
# Filter out first harvest cycle and calculate total costs per cell
cost_summary <- sim_results %>% 
  filter(harvest_cycle == 1) %>% 
  select(cell, month, harvest_cycle) %>% 
  left_join(cashflow) %>% 
  filter(cell %in% main_npv$cell) %>% 
  group_by(eez, cell) %>% 
  summarize(capital_cost = sum(c_costs, na.rm = T),
            labor_cost   = sum(total_monthly_labor, na.rm = T),
            fuel_cost    = sum(mo_fuel_cost, na.rm = T),
            feed_cost    = sum(feed_cost, na.rm = T),
            seed_cost    = sum(fingerling_cost, na.rm = T)) %>% 
  select(-cell)

# Summarize average farm costs per EEZ
eez_cost_summary <- cost_summary %>% 
  group_by(eez) %>% 
  summarize_all(mean, na.rm = T) %>% 
  left_join(npv_df %>% 
              select(eez, country) %>% distinct())

# Summarize average farm costs per EEZ
carib_cost_summary <- cost_summary %>% 
  ungroup() %>% 
  summarize_all(mean, na.rm = T) %>% 
  mutate(country = 'Caribbean')
```

```{r}
# Stacked barplot of average farm cost per eez
# Consider doing only for one harvest cycle to make results more comparable to literature estimates (e.g. 70% of op costs)

# Barplot
eez_cost_summary %>% 
  select(-eez) %>% 
  filter(is.na(country)==F) %>% 
  gather(key = 'category', value = 'cost', 1:5) %>% 
  ggplot(aes(x = country, y = cost, fill = fct_relevel(category, c('seed_cost','feed_cost'), after = Inf))) +
  geom_bar(stat = 'identity', position = 'fill') +
  scale_y_continuous(breaks = seq(from = 0, to = 1, by = 0.1), labels = paste0(seq(from = 0, to = 100, by = 10),'%')) +
  scale_fill_viridis(option = 'D', discrete = T) +
  labs(y    = '% of total cost',
       x    = NULL,
       fill = 'Cost category') +
  coord_flip() +
  theme_minimal()
```

## Profitability and harvest by country

```{r}
npv_cntry_plot_df <- npv_cntry_summary %>% 
  ungroup() %>% 
  filter(prices == 8.62 & discounts == 0) %>% 
  filter(stat %in% c('n', 'mean')) %>% 
  select(country, variable, stat, value) %>% 
  spread(variable, value) %>% 
  group_by(country) %>% 
  mutate(farms = npv[stat == 'n']) %>% 
  filter(stat == 'mean')

ggplot(npv_cntry_plot_df, aes(x = total_harvest, y = npv)) +
  geom_point(aes(size = farms)) +
  geom_label_repel(aes(label = country)) +
  scale_size_continuous(breaks = seq(from = 1000, to = 9000, by = 1000)) +
  scale_x_continuous(labels = comma) +
  labs(x = 'Average farm harvest (kg)',
       y = 'Average farm net present value (NPV)',
       size = "Number of farms") +
  theme_minimal()
```

